#!/usr/bin/env python3

import colorama
import pefile
import sys

from version import Version


class Program:
    EXIT_SUCCESS = 0
    EXIT_FAILURE = 1
    PROGRAM_NAME = Version.get_project_name()
    PROGRAM_VERSION = Version.get_version()

    def __init__(self, args):
        self.args = args
        self.exe_to_emulate = None

        self.printBanner()
        self.parseArguments()
        self.emulateEXE(self.getEXEToEmulate())

    def emulateEXE(self, exe):
        pass

    def getEXEToEmulate(self):
        if self.exe_to_emulate is None:
            print("ERROR: The EXE to emulate is not set!")
            sys.exit(self.EXIT_FAILURE)
        else:
            return self.exe_to_emulate

    def getProgramArguments(self):
        return self.args

    def getBannerString(self):
        return f"{self.PROGRAM_NAME} {self.PROGRAM_VERSION}"

    def getTestDirectory(self):
        return self.test_directory()

    def parseArguments(self):
        if len(self.args) != 2:
            print("ERROR: Wrong argument number!")
            sys.exit(self.EXIT_FAILURE)
        else:
            self.setEXEToEmulate(self.args[1])

    def printBanner(self):
        print(self.getBannerString())

    def setEXEToEmulate(self, exe_path):
        self.exe_to_emulate = exe_path


def main(args):
    program = Program(args)
    return Program.EXIT_SUCCESS


if __name__ == "__main__":
    sys.exit(main(sys.argv))
